### ISSUE TITLE
Writing

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#103]
- [ ] Dataset
   - [ ] Origin
   - [ ] Train/test/holdout split
   - [ ] Description of statistics
- [ ] Imbalanced data
   - [ ] Distribution of classes
   - [x] Random over- and under- samplings
- [x] Preprocessing - @wtaisner, @annprzy 
   - [x] shell
   - [x] uniform
   - [x] kmeans
   - [x] PCA
   - [x] normals
- [ ] Models - @konradszewczyk 
   - [ ] TransLoc3D
   - [ ] MinkLoc3DV2
   - [ ] RiConv (?)
   - [ ] Models implemented in MinkowskiEngine
- [ ] Runtime environment - @jkarolczak 
   - [ ] MLOps
   - [ ] hardware
   - [ ] MinkowskiEngine
   - [ ] DevOps
   - [ ] Testing, CI
   - [ ] Storage - Azure

**Comment by wtaisner** [comment]
I would also add, just to remember:
- distribution of classes
- sampling methods

**Comment by jkarolczak** [comment]
@wtaisner added!

**Comment by wtaisner** [comment]
I think it's done
