### ISSUE TITLE
last holdout is not calculating in bulk train and eval

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligand-classification#107]
for the reference see run 654 and no holdout run after (655 was already a different run, trashed)

**Comment by jkarolczak** [comment]
I'm delighted to give a pleasant announcement that this is not our oversight. In this particular case, for reasons unknown to me, Neptune decided to not log this experiment. I managed to run bulk experiments and all (including the last holdout) have been logged. For evidence see runs 717-720. All these runs are tagged with dev-107.
