### ISSUE TITLE
update of github actions

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligand-classification#111]
general idea is to test the following functionalities with github actions:
- [ ] install ME for tests to pass
- [ ] test, whether we can check building of docker containers/compse

**Comment by jkarolczak** [comment]
We cannot use Cuda on GitHub-hosted runners, because they run on machines without GPU. Thus we need our own runner to use Cuda. We cannot satisfy this requirement. Thus I recommend using `@pytest.mark.skip` as the universal issue resolver

**Comment by wtaisner** [comment]
Should we discard the issue & branch, or do we want to incorporate ME into our branch?

**Comment by jkarolczak** [comment]
afaik we don't test anything depending on ME, so imo we can get rid of installing ME. It should speed up tests.

**Comment by wtaisner** [comment]
agree, closing the issue as resolved
