### ISSUE TITLE
limit number of voxels in each blob

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligand-classification#16]
- [x]  random choice (done 0026ff5 )
- [x] clustering - #23 
- [x] suface/shell - #22 
- [x] uniform - #24 
- [x] #29

**Comment by jkarolczak** [comment]
0026ff5230b53907317bdc58baa9799a4c240eaf

**Comment by wtaisner** [comment]
weird way of mentioning an issue but ok
