### ISSUE TITLE
add git workflow to the project

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligand-classification#27]
add basic CI/CD functionality into the repository:

- [ ] add tests to pipeline module (use pytest)
- [ ] find a tool and deploy it, so that after each push to branch, a pipeline running tests will be run; should tests fail, merge should be forbidden

**Comment by wtaisner** [comment]
- [ ] find the coolest badges available

**Comment by jkarolczak** [comment]
@wtaisner 
![Imgur](https://i.imgur.com/d2UwHAk.jpg)

**Comment by jkarolczak** [comment]
Closed by #30
