### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#40]
The following packages are missing in the container:
- addict
- yapf
- neptune-client

**Comment by jkarolczak** [comment]
torchmetrics bump version, I highly recommend >= 0.8.0

**Comment by wtaisner** [comment]
also, neptune-client should be upgraaded to >= 0.14.2 or sth like this, torchmetrics can be bumped even higer

**Comment by jkarolczak** [comment]
@konradszewczyk rebuild the image (@wtaisner ask to add "asap" here), all changes have been done in dockerfile
