### ISSUE TITLE
Ania popatrz na kmeansy

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#46]

**Comment by wtaisner** [comment]
Ania, patrzyłaś już na kmeansy?

**Comment by annprzy** [comment]
Już nawet kilka razy

**Comment by jkarolczak** [comment]
A spojrzysz jeszcze kilkanaście?

**Comment by annprzy** [comment]
z mojego intensywnego patrzenia wynika, że 2 iteracje będą ok
