### ISSUE TITLE
wipe every trace of softmax from the repository

### ISSUE THREAD

**Issue by wtaisner** [jkarolczak/ligand-classification#60]
leave no survivors, take no prisoners

**Comment by jkarolczak** [comment]
Is the below solution a proper strategy for dealing with this issue?
![force](https://memegenerator.net/img/instances/48682221.jpg)

**Comment by wtaisner** [comment]
yes, but you also should wipe github databases with a magnet, delete this repo and create a new one, so that no sign is preserved

**Comment by wtaisner** [comment]
oh but blowing stuff is cool as heck, make sure to DM me some pictures
