### ISSUE TITLE
Add all .yaml files to .gitignore

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#81]
What do you think about the idea? Please, give your opinion in comment

**Comment by wtaisner** [comment]
I consider this to be a good idea, since all metadata are stored in neptune anyway, while .yaml files make a mess during our work on adas

**Comment by jkarolczak** [comment]
Okay, thank you for expressing your viewpoint. We will add it in the newest release. I'm going to close the issue now.
