### ISSUE TITLE
CMB scores

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#86]
I put them here, because slack may eat them one day. 

Accuracy: 0.672
Top-5 accuracy: 0.885
Top-10 accuracy: 0.936
Top-20 accuracy: 0.966
Macro recall: 0.343
Micro recall: 0.672
Micro precision: 0.683
Micro F1: 0.653
Kappa: 0.612
G-mean: 0.169
Brier score: 0.471

**Comment by wtaisner** [comment]
this is 200IQ big brain time move
