### ISSUE TITLE
Debug PointNet

### ISSUE THREAD

**Issue by jkarolczak** [jkarolczak/ligand-classification#92]

**Comment by jkarolczak** [comment]
I did a local test on a tiny dataset: https://app.neptune.ai/o/LIGANDS/org/LIGANDS/e/LIGANDS-534/charts and spotted only a little bit of smoke between epochs 1 and 3. But after epoch 3 learning curve looks casual. Maybe we should find proper hyperparametrization to make the model leave the optimum asap?

**Comment by wtaisner** [comment]
this stuff doesn't work
